services:
  app:
    build: .
    container_name: ap
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - internet
      - localnet

  postgres:
    image: postgres:17.4
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - localnet

  nginx:
    image: nginx:latest
    container_name: ng
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - app
    networks:
      - internet

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge